language: cpp
dist: focal
matrix:
  include:
  - os: linux
    env: PYTHON=3.8
  # - os: osx
  #   env: PYTHON=3.8
  # - os: windows
  #   env: PYTHON=3.8
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    # Install Intel OpenCL
    wget --no-check-certificate -qO - https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo apt-key add -
    sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
    
    sudo apt update
    sudo apt install intel-oneapi-runtime-opencl
    sudo apt install gcc-10 g++-10
    sudo apt install python$PYTHON python$PYTHON-venv python$PYTHON-dev
    sudo apt install opencl-headers
    sudo apt install ocl-icd-opencl-dev

    export CC="ccache gcc-10"
  fi

  python$PYTHON -m venv venv
  source venv/bin/activate
  python -m pip install pyarrow
  python -m pip install pytest
  python -m pip install scipy
  python -m pip install pandas
  python -m pip install wheel

install:
  python -m pip install .
script:
- python -m pytest