name: Create release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_win:
    name: Create Windows wheels.
    
    runs-on: windows-latest
        
    steps:
    
    - name: Download OCL SDK
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/files/1406216/lightOCLSDK.zip"
        target: "."
        
    - name: Check directory
      run: |
        tree .
        
    - name: Unzip SDK
      run: |
        mkdir OCLSDK
        7z x lightOCLSDK.zip -oOCLSDK
        
    - name: Check unzip
      run: |
        tree .
