name: Create release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_win:
    name: Create Windows wheels.
    
    runs-on: windows-latest
        
    steps:    
    - name: Install OpenCL dependencies
      run: choco install opencl-intel-cpu-runtime
    
    - name: Find OpenCL installation
      run: |
        tree C:\Program Files (x86)
        tree C:\Program Files
